services:
    _defaults:
        public: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    clickpress_newspodcasts.listener.generatexml:
        class: Clickpress\NewsPodcasts\EventListener\GenerateXmlFilesListener
        tags: [ 'terminal42_service_annotation' ]

    clickpress_newspodcasts.listener.removeoldfeeds:
        class: Clickpress\NewsPodcasts\EventListener\RemoveOldFeedsListener
        tags: [ 'terminal42_service_annotation' ]
